parameters:
    crevillo.ezpricesbundle.fieldType.ezprice.externalStorage.class: Crevillo\EzPricesBundle\eZ\Publish\Core\FieldType\Price\PriceStorage

services:
    crevillo.ezpricesbundle.fieldType.ezprice.externalStorage:
        class: %crevillo.ezpricesbundle.fieldType.ezprice.externalStorage.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: ezprice}